#!/usr/bin/env python3
"""Wrap the GLSL kernels in raw string literals: ShaderSources.h, a table of every file's name and
text, from which VulkanContext.cpp expands the #include lines and hands each kernel to the core's
compiler.

    embed_shaders.py OUTPUT INPUT...

An INPUT that is a directory stands for the .comp and .glsl files in it. Each file is split into
literal pieces of a few thousand characters, which concatenate back to the
whole text and keep under MSVC's limit for a single string literal. The output is only rewritten
when its content changes, so untouched kernels never dirty the build.
"""
import os
import sys

DELIM = "MVGPUSHADER"
PIECE = 8000


def literal(text):
    pieces = [text[i:i + PIECE] for i in range(0, len(text), PIECE)] or [""]
    return "\n        ".join(f'R"{DELIM}({p}){DELIM}"' for p in pieces)


def main() -> int:
    dst, sources = sys.argv[1], []
    for arg in sys.argv[2:]:
        if os.path.isdir(arg):
            sources += [os.path.join(arg, f) for f in os.listdir(arg) if f.endswith((".comp", ".glsl"))]
        else:
            sources.append(arg)
    lines = [
        "// Generated by src/shaders/embed_shaders.py from the kernels in src/shaders; do not edit.",
        "#pragma once",
        "",
        "struct ShaderSource {",
        "    const char *name;",
        "    const char *text;",
        "};",
        "",
        "static const ShaderSource kShaderSources[] = {",
    ]
    for src in sorted(sources, key=os.path.basename):
        with open(src, encoding="utf-8") as f:
            text = f.read().replace("\r\n", "\n")
        if f"){DELIM}\"" in text:
            print(f"{src}: contains the raw string delimiter ){DELIM}\", pick another", file=sys.stderr)
            return 1
        lines.append(f'    {{ "{os.path.basename(src)}",')
        lines.append(f"        {literal(text)} }},")
    lines += ["};", ""]
    out = "\n".join(lines)
    try:
        with open(dst, encoding="utf-8", newline="") as f:
            if f.read() == out:
                return 0
    except OSError:
        pass
    with open(dst, "w", encoding="utf-8", newline="") as f:
        f.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
